select
	HIS.ADDRESS_ID --地址識別碼
	,REPLACE(REPLACE(REGEXP_REPLACE(HIS.HIS_ADR, '^\d+',''), '臺灣省',''),'福建省','') as HIS_ADR --歷史地址
	,'' as FULL_ADDRESS --完整地址
	,STD.WGS_X as X --座標x
	,STD.WGS_Y as Y --座標y
	,STD.ADR_VERSION --母體版本
	,HIS.UPDATE_DT --戶政更新日期
	,UPD.UPDATE_TYPE --戶政更新狀態
from addr_ods.IBD_TB_IH_CHANGE_DOORPLATE_HIS HIS
left join addr_ods.IBD_TB_ADDR_CODE_OF_DATA_STANDARD STD
	on HIS.ADDRESS_ID = STD.ADDRESS_ID
	and HIS.ADR_VERSION = STD.ADR_VERSION
left join addr_stage.IBD_TB_HISTORY_CODE_UPDATE UPD
	on HIS.UPDATE_CODE = UPD.UPDATE_CODE
where 1 = 1
	and HIS.ADDRESS_ID = :addressId
	--目前先從 IBD_TB_ADDR_CODE_OF_DATA_STANDARD 撈最大版本
    AND STD.ADR_VERSION IN (SELECT MAX( ADR_VERSION ) FROM ADDR_ODS.IBD_TB_ADDR_CODE_OF_DATA_STANDARD)
union
select
	ADDRESS_ID,
	'' as HIS_ADR,--歷史地址
	FULL_ADDRESS, --完整地址
	WGS_X as X,
	WGS_Y as Y,
	ADR_VERSION,
	'-' UPDATE_DT,
	'現行門牌' UPDATE_TYPE
from addr_ods.IBD_TB_ADDR_CODE_OF_DATA_STANDARD
where ADDRESS_ID = :addressId
----目前先從 IBD_TB_ADDR_CODE_OF_DATA_STANDARD 撈最大版本 adrVersion
AND ADR_VERSION IN (SELECT MAX( ADR_VERSION ) FROM ADDR_ODS.IBD_TB_ADDR_CODE_OF_DATA_STANDARD)
--AND ADR_VERSION IN (:adrVersion)
