WITH SUBQUERY AS ( 
SELECT A.*
--,B.*
,B.NUM_FLR_POS,B.ROOM_ID_SN,B.NUM_FLR_ID,B.ROAD_AREA_SN
FROM ADDR_ODS.IBD_TB_ADDR_CODE_OF_DATA_STANDARD A
INNER JOIN ( 
SELECT * 
FROM addr_ods.IBD_TB_ADDR_DATA_REPOSITORY_NEW 
WHERE ADR_VERSION in (select max(ADR_VERSION) from addr_ods.IBD_TB_ADDR_DATA_REPOSITORY_NEW )
AND SEQ in (:SEQ)
 ) B 
ON A.SEQ = B.SEQ
)
SELECT * 
FROM SUBQUERY
